- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
  - name: Updating cache
    become: true
    apt:
      update_cache: true
    tags:
      - install
      - core
  tasks:
    - name: "ssh"
      ansible.builtin.include_tasks: tasks/ssh.yml
    - name: "zsh"
      ansible.builtin.include_tasks: tasks/zsh-setup.yml
    - name: "node"
      ansible.builtin.include_tasks: tasks/node.yml
    - name: "npm packages"
      ansible.builtin.include_tasks: tasks/npm-packages.yml
    - name: "Git config"
      ansible.builtin.include_tasks: tasks/git.yml
    - name: "dotfiles"
      ansible.builtin.include_tasks: tasks/dotfiles.yml
